/*==========================================================================*\
 |  _ScriptFile.java
 |*-------------------------------------------------------------------------*|
 |  Created by eogenerator
 |  DO NOT EDIT.  Make changes to ScriptFile.java instead.
 |*-------------------------------------------------------------------------*|
 |  Copyright (C) 2006 Virginia Tech
 |
 |  This file is part of Web-CAT.
 |
 |  Web-CAT is free software; you can redistribute it and/or modify
 |  it under the terms of the GNU General Public License as published by
 |  the Free Software Foundation; either version 2 of the License, or
 |  (at your option) any later version.
 |
 |  Web-CAT is distributed in the hope that it will be useful,
 |  but WITHOUT ANY WARRANTY; without even the implied warranty of
 |  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 |  GNU General Public License for more details.
 |
 |  You should have received a copy of the GNU General Public License
 |  along with Web-CAT; if not, write to the Free Software
 |  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 |
 |  Project manager: Stephen Edwards <edwards@cs.vt.edu>
 |  Virginia Tech CS Dept, 660 McBryde Hall (0106), Blacksburg, VA 24061 USA
 \*==========================================================================*/

package net.sf.webcat.grader;

import com.webobjects.foundation.*;
import com.webobjects.eocontrol.*;
import java.util.Enumeration;

// -------------------------------------------------------------------------
/**
 * An automatically generated EOGenericRecord subclass.  DO NOT EDIT.
 * To change, use EOModeler, or make additions in
 * ScriptFile.java.
 *
 * @author Generated by eogenerator
 * @version version suppressed to control auto-generation
 */
public abstract class _ScriptFile
    extends er.extensions.ERXGenericRecord
    implements net.sf.webcat.core.MutableContainer.MutableContainerOwner
{
    //~ Constructors ..........................................................

    // ----------------------------------------------------------
    /**
     * Creates a new _ScriptFile object.
     */
    public _ScriptFile()
    {
        super();
    }


    //~ Constants (for key names) .............................................

    // Attributes ---
    public static final String CONFIG_DESCRIPTION_KEY = "configDescription";
    public static final String DEFAULT_CONFIG_SETTINGS_KEY = "defaultConfigSettings";
    public static final String IS_CONFIG_FILE_KEY = "isConfigFile";
    public static final String IS_PUBLISHED_KEY = "isPublished";
    public static final String LAST_MODIFIED_KEY = "lastModified";
    public static final String MAIN_FILE_NAME_KEY = "mainFileName";
    public static final String NAME_KEY = "name";
    public static final String SUBDIR_NAME_KEY = "subdirName";
    public static final String UPDATE_MUTABLE_FIELDS_KEY = "updateMutableFields";
    public static final String UPLOADED_FILE_NAME_KEY = "uploadedFileName";
    // To-one relationships ---
    public static final String AUTHOR_KEY = "author";
    public static final String LANGUAGE_KEY = "language";
    // To-many relationships ---
    public static final String COURSE_OFFERINGS_KEY = "courseOfferings";
    public static final String STEPS_KEY = "steps";
    public static final String ENTITY_NAME = "ScriptFile";


    //~ Methods ...............................................................

    //-- Local mutable cache --
    private net.sf.webcat.core.MutableDictionary configDescriptionCache;
    private NSData configDescriptionRawCache;

    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>configDescription</code> value.
     * @return the value of the attribute
     */
    public net.sf.webcat.core.MutableDictionary configDescription()
    {
    	NSData dbValue = 
            (NSData)storedValueForKey( "configDescription" );
        if ( configDescriptionRawCache != dbValue )
        {
            if ( dbValue != null && dbValue.equals( configDescriptionRawCache ) )
            {
                // They are still equal, so just update the raw cache
                configDescriptionRawCache = dbValue;
            }
            else
            {
                // Underlying attribute may have changed because
                // of a concurrent update through another editing
                // context, so throw away current values.
                configDescriptionRawCache = dbValue;
                net.sf.webcat.core.MutableDictionary newValue =
                    net.sf.webcat.core.MutableDictionary
                    .objectWithArchiveData( dbValue );
                if ( configDescriptionCache != null )
                {
                    configDescriptionCache.copyFrom( newValue );
                }
                else
                {
                    configDescriptionCache = newValue;
                }
                configDescriptionCache.setOwner( this );
                setUpdateMutableFields( true );
            }
        }
        else if ( dbValue == null && configDescriptionCache == null )
        { 
            configDescriptionCache = 
                net.sf.webcat.core.MutableDictionary
                .objectWithArchiveData( dbValue );
             configDescriptionCache.setOwner( this );
             setUpdateMutableFields( true );
        }
        return configDescriptionCache;
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>configDescription</code>
     * property.
     * 
     * @param value The new value for this property
     */
    public void setConfigDescription( net.sf.webcat.core.MutableDictionary value )
    {
        if ( configDescriptionCache == null )
        {
            configDescriptionCache = value;
            value.setHasChanged( false );
            configDescriptionRawCache = value.archiveData();
            takeStoredValueForKey( configDescriptionRawCache, "configDescription" );
        }
        else if ( configDescriptionCache != value )  // ( configDescriptionCache != null )
        {
            configDescriptionCache.copyFrom( value );
            setUpdateMutableFields( true );
        }
        else  // ( configDescriptionCache == non-null value )
        {
            // no nothing
        }
    }


    // ----------------------------------------------------------
    /**
     * Clear the value of this object's <code>configDescription</code>
     * property.
     */
    public void clearConfigDescription()
    {
        takeStoredValueForKey( null, "configDescription" );
        configDescriptionRawCache = null;
        configDescriptionCache = null;
    }


    //-- Local mutable cache --
    private net.sf.webcat.core.MutableDictionary defaultConfigSettingsCache;
    private NSData defaultConfigSettingsRawCache;

    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>defaultConfigSettings</code> value.
     * @return the value of the attribute
     */
    public net.sf.webcat.core.MutableDictionary defaultConfigSettings()
    {
    	NSData dbValue = 
            (NSData)storedValueForKey( "defaultConfigSettings" );
        if ( defaultConfigSettingsRawCache != dbValue )
        {
            if ( dbValue != null && dbValue.equals( defaultConfigSettingsRawCache ) )
            {
                // They are still equal, so just update the raw cache
                defaultConfigSettingsRawCache = dbValue;
            }
            else
            {
                // Underlying attribute may have changed because
                // of a concurrent update through another editing
                // context, so throw away current values.
                defaultConfigSettingsRawCache = dbValue;
                net.sf.webcat.core.MutableDictionary newValue =
                    net.sf.webcat.core.MutableDictionary
                    .objectWithArchiveData( dbValue );
                if ( defaultConfigSettingsCache != null )
                {
                    defaultConfigSettingsCache.copyFrom( newValue );
                }
                else
                {
                    defaultConfigSettingsCache = newValue;
                }
                defaultConfigSettingsCache.setOwner( this );
                setUpdateMutableFields( true );
            }
        }
        else if ( dbValue == null && defaultConfigSettingsCache == null )
        { 
            defaultConfigSettingsCache = 
                net.sf.webcat.core.MutableDictionary
                .objectWithArchiveData( dbValue );
             defaultConfigSettingsCache.setOwner( this );
             setUpdateMutableFields( true );
        }
        return defaultConfigSettingsCache;
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>defaultConfigSettings</code>
     * property.
     * 
     * @param value The new value for this property
     */
    public void setDefaultConfigSettings( net.sf.webcat.core.MutableDictionary value )
    {
        if ( defaultConfigSettingsCache == null )
        {
            defaultConfigSettingsCache = value;
            value.setHasChanged( false );
            defaultConfigSettingsRawCache = value.archiveData();
            takeStoredValueForKey( defaultConfigSettingsRawCache, "defaultConfigSettings" );
        }
        else if ( defaultConfigSettingsCache != value )  // ( defaultConfigSettingsCache != null )
        {
            defaultConfigSettingsCache.copyFrom( value );
            setUpdateMutableFields( true );
        }
        else  // ( defaultConfigSettingsCache == non-null value )
        {
            // no nothing
        }
    }


    // ----------------------------------------------------------
    /**
     * Clear the value of this object's <code>defaultConfigSettings</code>
     * property.
     */
    public void clearDefaultConfigSettings()
    {
        takeStoredValueForKey( null, "defaultConfigSettings" );
        defaultConfigSettingsRawCache = null;
        defaultConfigSettingsCache = null;
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>isConfigFile</code> value.
     * @return the value of the attribute
     */
    public boolean isConfigFile()
    {
        Number result =
            (Number)storedValueForKey( "isConfigFile" );
        return ( result == null )
            ? false
            : ( result.intValue() > 0 );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>isConfigFile</code>
     * property.
     * 
     * @param value The new value for this property
     */
    public void setIsConfigFile( boolean value )
    {
        Number actual =
            er.extensions.ERXConstant.integerForInt( value ? 1 : 0 );
        takeStoredValueForKey( actual, "isConfigFile" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>isConfigFile</code> value.
     * @return the value of the attribute
     */
    public Number isConfigFileRaw()
    {
        return (Number)storedValueForKey( "isConfigFile" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>isConfigFile</code>
     * property.
     * 
     * @param value The new value for this property
     */
    public void setIsConfigFileRaw( Number value )
    {
        takeStoredValueForKey( value, "isConfigFile" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>isPublished</code> value.
     * @return the value of the attribute
     */
    public boolean isPublished()
    {
        Number result =
            (Number)storedValueForKey( "isPublished" );
        return ( result == null )
            ? false
            : ( result.intValue() > 0 );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>isPublished</code>
     * property.
     * 
     * @param value The new value for this property
     */
    public void setIsPublished( boolean value )
    {
        Number actual =
            er.extensions.ERXConstant.integerForInt( value ? 1 : 0 );
        takeStoredValueForKey( actual, "isPublished" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>isPublished</code> value.
     * @return the value of the attribute
     */
    public Number isPublishedRaw()
    {
        return (Number)storedValueForKey( "isPublished" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>isPublished</code>
     * property.
     * 
     * @param value The new value for this property
     */
    public void setIsPublishedRaw( Number value )
    {
        takeStoredValueForKey( value, "isPublished" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>lastModified</code> value.
     * @return the value of the attribute
     */
    public NSTimestamp lastModified()
    {
        return (NSTimestamp)storedValueForKey( "lastModified" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>lastModified</code>
     * property.
     * 
     * @param value The new value for this property
     */
    public void setLastModified( NSTimestamp value )
    {
        takeStoredValueForKey( value, "lastModified" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>mainFileName</code> value.
     * @return the value of the attribute
     */
    public String mainFileName()
    {
        return (String)storedValueForKey( "mainFileName" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>mainFileName</code>
     * property.
     * 
     * @param value The new value for this property
     */
    public void setMainFileName( String value )
    {
        takeStoredValueForKey( value, "mainFileName" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>name</code> value.
     * @return the value of the attribute
     */
    public String name()
    {
        return (String)storedValueForKey( "name" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>name</code>
     * property.
     * 
     * @param value The new value for this property
     */
    public void setName( String value )
    {
        takeStoredValueForKey( value, "name" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>subdirName</code> value.
     * @return the value of the attribute
     */
    public String subdirName()
    {
        return (String)storedValueForKey( "subdirName" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>subdirName</code>
     * property.
     * 
     * @param value The new value for this property
     */
    public void setSubdirName( String value )
    {
        takeStoredValueForKey( value, "subdirName" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>updateMutableFields</code> value.
     * @return the value of the attribute
     */
    public boolean updateMutableFields()
    {
        Number result =
            (Number)storedValueForKey( "updateMutableFields" );
        return ( result == null )
            ? false
            : ( result.intValue() > 0 );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>updateMutableFields</code>
     * property.
     * 
     * @param value The new value for this property
     */
    public void setUpdateMutableFields( boolean value )
    {
        Number actual =
            er.extensions.ERXConstant.integerForInt( value ? 1 : 0 );
        takeStoredValueForKey( actual, "updateMutableFields" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>updateMutableFields</code> value.
     * @return the value of the attribute
     */
    public Number updateMutableFieldsRaw()
    {
        return (Number)storedValueForKey( "updateMutableFields" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>updateMutableFields</code>
     * property.
     * 
     * @param value The new value for this property
     */
    public void setUpdateMutableFieldsRaw( Number value )
    {
        takeStoredValueForKey( value, "updateMutableFields" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>uploadedFileName</code> value.
     * @return the value of the attribute
     */
    public String uploadedFileName()
    {
        return (String)storedValueForKey( "uploadedFileName" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>uploadedFileName</code>
     * property.
     * 
     * @param value The new value for this property
     */
    public void setUploadedFileName( String value )
    {
        takeStoredValueForKey( value, "uploadedFileName" );
    }


    // ----------------------------------------------------------
    /**
     * Called just before this object is saved to the database.
     */
    public void saveMutables()
    {
        if ( configDescriptionCache != null
            && configDescriptionCache.hasChanged() )
        {
            configDescriptionRawCache = configDescriptionCache.archiveData();
            takeStoredValueForKey( configDescriptionRawCache, "configDescription" );
            configDescriptionCache.setHasChanged( false );
        }
        if ( defaultConfigSettingsCache != null
            && defaultConfigSettingsCache.hasChanged() )
        {
            defaultConfigSettingsRawCache = defaultConfigSettingsCache.archiveData();
            takeStoredValueForKey( defaultConfigSettingsRawCache, "defaultConfigSettings" );
            defaultConfigSettingsCache.setHasChanged( false );
        }

        setUpdateMutableFields( false );
    }


    // ----------------------------------------------------------
    /**
     * Called just before this object is saved to the database.
     */
    public void willUpdate()
    {
        saveMutables();
        super.willUpdate();
    }


    // ----------------------------------------------------------
    /**
     * Called just before this object is inserted into the database.
     */
    public void willInsert()
    {
        saveMutables();
        super.willInsert();
    }


    // ----------------------------------------------------------
    /**
     * Called when the object is invalidated.
     */
    public void flushCaches()
    {
        configDescriptionCache = null;
        configDescriptionRawCache  = null;
        defaultConfigSettingsCache = null;
        defaultConfigSettingsRawCache  = null;
        setUpdateMutableFields( false );
        super.flushCaches();
    }


    // ----------------------------------------------------------
    /**
     * Called when an owned mutable container object is changed.
     */
    public void mutableContainerHasChanged()
    {
        setUpdateMutableFields( true );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entity pointed to by the <code>author</code>
     * relationship.
     * @return the entity in the relationship
     */
    public net.sf.webcat.core.User author()
    {
        return (net.sf.webcat.core.User)storedValueForKey( "author" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>authenticationDomain</code>
     * relationship (DO NOT USE--instead, use
     * <code>setAuthorRelationship()</code>.
     * This method is provided for WebObjects use.
     * 
     * @param value The new entity to relate to
     */
    public void setAuthor( net.sf.webcat.core.User value )
    {
        takeStoredValueForKey( value, "author" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>authenticationDomain</code>
     * relationship.  This method is a type-safe version of
     * <code>addObjectToBothSidesOfRelationshipWithKey()</code>.
     * 
     * @param value The new entity to relate to
     */
    public void setAuthorRelationship(
        net.sf.webcat.core.User value )
    {
        if ( value == null )
        {
            net.sf.webcat.core.User object = author();
            if ( object != null )
                removeObjectFromBothSidesOfRelationshipWithKey( object, "author" );
        }
        else
        {
            addObjectToBothSidesOfRelationshipWithKey( value, "author" );
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entity pointed to by the <code>language</code>
     * relationship.
     * @return the entity in the relationship
     */
    public net.sf.webcat.core.Language language()
    {
        return (net.sf.webcat.core.Language)storedValueForKey( "language" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>authenticationDomain</code>
     * relationship (DO NOT USE--instead, use
     * <code>setLanguageRelationship()</code>.
     * This method is provided for WebObjects use.
     * 
     * @param value The new entity to relate to
     */
    public void setLanguage( net.sf.webcat.core.Language value )
    {
        takeStoredValueForKey( value, "language" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>authenticationDomain</code>
     * relationship.  This method is a type-safe version of
     * <code>addObjectToBothSidesOfRelationshipWithKey()</code>.
     * 
     * @param value The new entity to relate to
     */
    public void setLanguageRelationship(
        net.sf.webcat.core.Language value )
    {
        if ( value == null )
        {
            net.sf.webcat.core.Language object = language();
            if ( object != null )
                removeObjectFromBothSidesOfRelationshipWithKey( object, "language" );
        }
        else
        {
            addObjectToBothSidesOfRelationshipWithKey( value, "language" );
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entities pointed to by the <code>courseOfferings</code>
     * relationship.
     * @return an NSArray of the entities in the relationship
     */
    public NSArray courseOfferings()
    {
        return (NSArray)storedValueForKey( "courseOfferings" );
    }


    // ----------------------------------------------------------
    /**
     * Replace the list of entities pointed to by the
     * <code>courseOfferings</code> relationship.
     * 
     * @param value The new set of entities to relate to
     */
    public void setCourseOfferings( NSMutableArray value )
    {
        takeStoredValueForKey( value, "courseOfferings" );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>courseOfferings</code>
     * relationship (DO NOT USE--instead, use
     * <code>addToCourseOfferingsRelationship()</code>.
     * This method is provided for WebObjects use.
     * 
     * @param value The new entity to relate to
     */
    public void addToCourseOfferings( net.sf.webcat.core.CourseOffering value )
    {
        NSMutableArray array = (NSMutableArray)courseOfferings();
        willChange();
        array.addObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>courseOfferings</code>
     * relationship (DO NOT USE--instead, use
     * <code>removeFromCourseOfferingsRelationship()</code>.
     * This method is provided for WebObjects use.
     * 
     * @param value The entity to remove from the relationship
     */
    public void removeFromCourseOfferings( net.sf.webcat.core.CourseOffering value )
    {
        NSMutableArray array = (NSMutableArray)courseOfferings();
        willChange();
        array.removeObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>courseOfferings</code>
     * relationship.
     * 
     * @param value The new entity to relate to
     */
    public void addToCourseOfferingsRelationship( net.sf.webcat.core.CourseOffering value )
    {
        addObjectToBothSidesOfRelationshipWithKey(
            value, "courseOfferings" );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>courseOfferings</code>
     * relationship.
     * 
     * @param value The entity to remove from the relationship
     */
    public void removeFromCourseOfferingsRelationship( net.sf.webcat.core.CourseOffering value )
    {
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "courseOfferings" );
    }


    // ----------------------------------------------------------
    /**
     * Create a brand new object that is a member of the
     * <code>courseOfferings</code> relationship.
     * 
     * @return The new entity
     */
    public net.sf.webcat.core.CourseOffering createCourseOfferingsRelationship()
    {
        EOClassDescription eoClassDesc = EOClassDescription
            .classDescriptionForEntityName( "CourseOffering" );
        EOEnterpriseObject eoObject = eoClassDesc
            .createInstanceWithEditingContext( editingContext(), null );
        editingContext().insertObject( eoObject );
        addObjectToBothSidesOfRelationshipWithKey(
            eoObject, "courseOfferings" );
        return (net.sf.webcat.core.CourseOffering)eoObject;
    }


    // ----------------------------------------------------------
    /**
     * Remove and then delete a specific entity that is a member of the
     * <code>courseOfferings</code> relationship.
     * 
     * @param value The entity to remove from the relationship and then delete
     */
    public void deleteCourseOfferingsRelationship( net.sf.webcat.core.CourseOffering value )
    {
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "courseOfferings" );
        editingContext().deleteObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove (and then delete, if owned) all entities that are members of the
     * <code>courseOfferings</code> relationship.
     */
    public void deleteAllCourseOfferingsRelationships()
    {
        Enumeration objects = courseOfferings().objectEnumerator();
        while ( objects.hasMoreElements() )
            deleteCourseOfferingsRelationship(
                (net.sf.webcat.core.CourseOffering)objects.nextElement() );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entities pointed to by the <code>steps</code>
     * relationship.
     * @return an NSArray of the entities in the relationship
     */
    public NSArray steps()
    {
        return (NSArray)storedValueForKey( "steps" );
    }


    // ----------------------------------------------------------
    /**
     * Replace the list of entities pointed to by the
     * <code>steps</code> relationship.
     * 
     * @param value The new set of entities to relate to
     */
    public void setSteps( NSMutableArray value )
    {
        takeStoredValueForKey( value, "steps" );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>steps</code>
     * relationship (DO NOT USE--instead, use
     * <code>addToStepsRelationship()</code>.
     * This method is provided for WebObjects use.
     * 
     * @param value The new entity to relate to
     */
    public void addToSteps( net.sf.webcat.grader.Step value )
    {
        NSMutableArray array = (NSMutableArray)steps();
        willChange();
        array.addObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>steps</code>
     * relationship (DO NOT USE--instead, use
     * <code>removeFromStepsRelationship()</code>.
     * This method is provided for WebObjects use.
     * 
     * @param value The entity to remove from the relationship
     */
    public void removeFromSteps( net.sf.webcat.grader.Step value )
    {
        NSMutableArray array = (NSMutableArray)steps();
        willChange();
        array.removeObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>steps</code>
     * relationship.
     * 
     * @param value The new entity to relate to
     */
    public void addToStepsRelationship( net.sf.webcat.grader.Step value )
    {
        addObjectToBothSidesOfRelationshipWithKey(
            value, "steps" );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>steps</code>
     * relationship.
     * 
     * @param value The entity to remove from the relationship
     */
    public void removeFromStepsRelationship( net.sf.webcat.grader.Step value )
    {
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "steps" );
    }


    // ----------------------------------------------------------
    /**
     * Create a brand new object that is a member of the
     * <code>steps</code> relationship.
     * 
     * @return The new entity
     */
    public net.sf.webcat.grader.Step createStepsRelationship()
    {
        EOClassDescription eoClassDesc = EOClassDescription
            .classDescriptionForEntityName( "Step" );
        EOEnterpriseObject eoObject = eoClassDesc
            .createInstanceWithEditingContext( editingContext(), null );
        editingContext().insertObject( eoObject );
        addObjectToBothSidesOfRelationshipWithKey(
            eoObject, "steps" );
        return (net.sf.webcat.grader.Step)eoObject;
    }


    // ----------------------------------------------------------
    /**
     * Remove and then delete a specific entity that is a member of the
     * <code>steps</code> relationship.
     * 
     * @param value The entity to remove from the relationship and then delete
     */
    public void deleteStepsRelationship( net.sf.webcat.grader.Step value )
    {
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "steps" );
        editingContext().deleteObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove (and then delete, if owned) all entities that are members of the
     * <code>steps</code> relationship.
     */
    public void deleteAllStepsRelationships()
    {
        Enumeration objects = steps().objectEnumerator();
        while ( objects.hasMoreElements() )
            deleteStepsRelationship(
                (net.sf.webcat.grader.Step)objects.nextElement() );
    }


}
